# Generated by Django 5.2.7 on 2025-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='bcc',
            field=models.TextField(blank=True, help_text='Comma-separated email addresses for BCC'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='cc',
            field=models.TextField(blank=True, help_text='Comma-separated email addresses for CC'),
        ),
    ]
