# Generated by Django 5.2.7 on 2025-10-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_emailcampaign_bcc_emailcampaign_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='bcc_groups',
            field=models.ManyToManyField(blank=True, related_name='bcc_campaigns', to='mailer.contactgroup'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='cc_groups',
            field=models.ManyToManyField(blank=True, related_name='cc_campaigns', to='mailer.contactgroup'),
        ),
    ]
