# Generated by Django 5.2.7 on 2025-10-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_emailcampaign_bcc_groups_emailcampaign_cc_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='html_content',
            field=models.TextField(blank=True, help_text='HTML version of the email'),
        ),
    ]
